// Code generated by ent, DO NOT EDIT.

package wallettransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCurrency, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceAfter, v))
}

// ReferenceType applies equality check predicate on the "reference_type" field. It's identical to ReferenceTypeEQ.
func ReferenceType(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldIdempotencyKey, v))
}

// RequestFingerprint applies equality check predicate on the "request_fingerprint" field. It's identical to RequestFingerprintEQ.
func RequestFingerprint(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldRequestFingerprint, v))
}

// OperatorID applies equality check predicate on the "operator_id" field. It's identical to OperatorIDEQ.
func OperatorID(v int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldOperatorID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldSource, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldUserID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldType, vs...))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldCurrency, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldBalanceAfter, v))
}

// ReferenceTypeEQ applies the EQ predicate on the "reference_type" field.
func ReferenceTypeEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceType, v))
}

// ReferenceTypeNEQ applies the NEQ predicate on the "reference_type" field.
func ReferenceTypeNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldReferenceType, v))
}

// ReferenceTypeIn applies the In predicate on the "reference_type" field.
func ReferenceTypeIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldReferenceType, vs...))
}

// ReferenceTypeNotIn applies the NotIn predicate on the "reference_type" field.
func ReferenceTypeNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldReferenceType, vs...))
}

// ReferenceTypeGT applies the GT predicate on the "reference_type" field.
func ReferenceTypeGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldReferenceType, v))
}

// ReferenceTypeGTE applies the GTE predicate on the "reference_type" field.
func ReferenceTypeGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldReferenceType, v))
}

// ReferenceTypeLT applies the LT predicate on the "reference_type" field.
func ReferenceTypeLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldReferenceType, v))
}

// ReferenceTypeLTE applies the LTE predicate on the "reference_type" field.
func ReferenceTypeLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldReferenceType, v))
}

// ReferenceTypeContains applies the Contains predicate on the "reference_type" field.
func ReferenceTypeContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldReferenceType, v))
}

// ReferenceTypeHasPrefix applies the HasPrefix predicate on the "reference_type" field.
func ReferenceTypeHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldReferenceType, v))
}

// ReferenceTypeHasSuffix applies the HasSuffix predicate on the "reference_type" field.
func ReferenceTypeHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldReferenceType, v))
}

// ReferenceTypeEqualFold applies the EqualFold predicate on the "reference_type" field.
func ReferenceTypeEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldReferenceType, v))
}

// ReferenceTypeContainsFold applies the ContainsFold predicate on the "reference_type" field.
func ReferenceTypeContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldReferenceType, v))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDContains applies the Contains predicate on the "reference_id" field.
func ReferenceIDContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldReferenceID, v))
}

// ReferenceIDHasPrefix applies the HasPrefix predicate on the "reference_id" field.
func ReferenceIDHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldReferenceID, v))
}

// ReferenceIDHasSuffix applies the HasSuffix predicate on the "reference_id" field.
func ReferenceIDHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldReferenceID, v))
}

// ReferenceIDEqualFold applies the EqualFold predicate on the "reference_id" field.
func ReferenceIDEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldReferenceID, v))
}

// ReferenceIDContainsFold applies the ContainsFold predicate on the "reference_id" field.
func ReferenceIDContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldReferenceID, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// RequestFingerprintEQ applies the EQ predicate on the "request_fingerprint" field.
func RequestFingerprintEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintNEQ applies the NEQ predicate on the "request_fingerprint" field.
func RequestFingerprintNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintIn applies the In predicate on the "request_fingerprint" field.
func RequestFingerprintIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintNotIn applies the NotIn predicate on the "request_fingerprint" field.
func RequestFingerprintNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintGT applies the GT predicate on the "request_fingerprint" field.
func RequestFingerprintGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldRequestFingerprint, v))
}

// RequestFingerprintGTE applies the GTE predicate on the "request_fingerprint" field.
func RequestFingerprintGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldRequestFingerprint, v))
}

// RequestFingerprintLT applies the LT predicate on the "request_fingerprint" field.
func RequestFingerprintLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldRequestFingerprint, v))
}

// RequestFingerprintLTE applies the LTE predicate on the "request_fingerprint" field.
func RequestFingerprintLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldRequestFingerprint, v))
}

// RequestFingerprintContains applies the Contains predicate on the "request_fingerprint" field.
func RequestFingerprintContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldRequestFingerprint, v))
}

// RequestFingerprintHasPrefix applies the HasPrefix predicate on the "request_fingerprint" field.
func RequestFingerprintHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldRequestFingerprint, v))
}

// RequestFingerprintHasSuffix applies the HasSuffix predicate on the "request_fingerprint" field.
func RequestFingerprintHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldRequestFingerprint, v))
}

// RequestFingerprintEqualFold applies the EqualFold predicate on the "request_fingerprint" field.
func RequestFingerprintEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldRequestFingerprint, v))
}

// RequestFingerprintContainsFold applies the ContainsFold predicate on the "request_fingerprint" field.
func RequestFingerprintContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldRequestFingerprint, v))
}

// OperatorIDEQ applies the EQ predicate on the "operator_id" field.
func OperatorIDEQ(v int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldOperatorID, v))
}

// OperatorIDNEQ applies the NEQ predicate on the "operator_id" field.
func OperatorIDNEQ(v int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldOperatorID, v))
}

// OperatorIDIn applies the In predicate on the "operator_id" field.
func OperatorIDIn(vs ...int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldOperatorID, vs...))
}

// OperatorIDNotIn applies the NotIn predicate on the "operator_id" field.
func OperatorIDNotIn(vs ...int64) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldOperatorID, vs...))
}

// OperatorIDIsNil applies the IsNil predicate on the "operator_id" field.
func OperatorIDIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldOperatorID))
}

// OperatorIDNotNil applies the NotNil predicate on the "operator_id" field.
func OperatorIDNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldOperatorID))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldSource, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.WalletTransaction {
	return predicate.WalletTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.WalletTransaction {
	return predicate.WalletTransaction(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOperator applies the HasEdge predicate on the "operator" edge.
func HasOperator() predicate.WalletTransaction {
	return predicate.WalletTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OperatorTable, OperatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOperatorWith applies the HasEdge predicate on the "operator" edge with a given conditions (other predicates).
func HasOperatorWith(preds ...predicate.User) predicate.WalletTransaction {
	return predicate.WalletTransaction(func(s *sql.Selector) {
		step := newOperatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WalletTransaction) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WalletTransaction) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WalletTransaction) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.NotPredicates(p))
}
