// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usermodelpermission"
)

// UserModelPermission is the model entity for the UserModelPermission schema.
type UserModelPermission struct {
	config `json:"-"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// RouteID holds the value of the "route_id" field.
	RouteID int64 `json:"route_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserModelPermissionQuery when eager-loading is set.
	Edges        UserModelPermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserModelPermissionEdges holds the relations/edges for other nodes in the graph.
type UserModelPermissionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Route holds the value of the route edge.
	Route *CompositeModelRoute `json:"route,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserModelPermissionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// RouteOrErr returns the Route value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserModelPermissionEdges) RouteOrErr() (*CompositeModelRoute, error) {
	if e.Route != nil {
		return e.Route, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: compositemodelroute.Label}
	}
	return nil, &NotLoadedError{edge: "route"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserModelPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usermodelpermission.FieldEnabled:
			values[i] = new(sql.NullBool)
		case usermodelpermission.FieldUserID, usermodelpermission.FieldRouteID, usermodelpermission.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case usermodelpermission.FieldCreatedAt, usermodelpermission.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserModelPermission fields.
func (_m *UserModelPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usermodelpermission.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usermodelpermission.FieldRouteID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field route_id", values[i])
			} else if value.Valid {
				_m.RouteID = value.Int64
			}
		case usermodelpermission.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case usermodelpermission.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case usermodelpermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usermodelpermission.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserModelPermission.
// This includes values selected through modifiers, order, etc.
func (_m *UserModelPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserModelPermission entity.
func (_m *UserModelPermission) QueryUser() *UserQuery {
	return NewUserModelPermissionClient(_m.config).QueryUser(_m)
}

// QueryRoute queries the "route" edge of the UserModelPermission entity.
func (_m *UserModelPermission) QueryRoute() *CompositeModelRouteQuery {
	return NewUserModelPermissionClient(_m.config).QueryRoute(_m)
}

// Update returns a builder for updating this UserModelPermission.
// Note that you need to call UserModelPermission.Unwrap() before calling this method if this UserModelPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserModelPermission) Update() *UserModelPermissionUpdateOne {
	return NewUserModelPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserModelPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserModelPermission) Unwrap() *UserModelPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserModelPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserModelPermission) String() string {
	var builder strings.Builder
	builder.WriteString("UserModelPermission(")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("route_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RouteID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserModelPermissions is a parsable slice of UserModelPermission.
type UserModelPermissions []*UserModelPermission
