// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usermodelpermission"
)

// UserModelPermissionCreate is the builder for creating a UserModelPermission entity.
type UserModelPermissionCreate struct {
	config
	mutation *UserModelPermissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserModelPermissionCreate) SetUserID(v int64) *UserModelPermissionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRouteID sets the "route_id" field.
func (_c *UserModelPermissionCreate) SetRouteID(v int64) *UserModelPermissionCreate {
	_c.mutation.SetRouteID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UserModelPermissionCreate) SetEnabled(v bool) *UserModelPermissionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UserModelPermissionCreate) SetNillableEnabled(v *bool) *UserModelPermissionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *UserModelPermissionCreate) SetCreatedBy(v int64) *UserModelPermissionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserModelPermissionCreate) SetCreatedAt(v time.Time) *UserModelPermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserModelPermissionCreate) SetNillableCreatedAt(v *time.Time) *UserModelPermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserModelPermissionCreate) SetUpdatedAt(v time.Time) *UserModelPermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserModelPermissionCreate) SetNillableUpdatedAt(v *time.Time) *UserModelPermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserModelPermissionCreate) SetUser(v *User) *UserModelPermissionCreate {
	return _c.SetUserID(v.ID)
}

// SetRoute sets the "route" edge to the CompositeModelRoute entity.
func (_c *UserModelPermissionCreate) SetRoute(v *CompositeModelRoute) *UserModelPermissionCreate {
	return _c.SetRouteID(v.ID)
}

// Mutation returns the UserModelPermissionMutation object of the builder.
func (_c *UserModelPermissionCreate) Mutation() *UserModelPermissionMutation {
	return _c.mutation
}

// Save creates the UserModelPermission in the database.
func (_c *UserModelPermissionCreate) Save(ctx context.Context) (*UserModelPermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserModelPermissionCreate) SaveX(ctx context.Context) *UserModelPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserModelPermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserModelPermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserModelPermissionCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := usermodelpermission.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usermodelpermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usermodelpermission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserModelPermissionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserModelPermission.user_id"`)}
	}
	if _, ok := _c.mutation.RouteID(); !ok {
		return &ValidationError{Name: "route_id", err: errors.New(`ent: missing required field "UserModelPermission.route_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UserModelPermission.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "UserModelPermission.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserModelPermission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserModelPermission.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserModelPermission.user"`)}
	}
	if len(_c.mutation.RouteIDs()) == 0 {
		return &ValidationError{Name: "route", err: errors.New(`ent: missing required edge "UserModelPermission.route"`)}
	}
	return nil
}

func (_c *UserModelPermissionCreate) sqlSave(ctx context.Context) (*UserModelPermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *UserModelPermissionCreate) createSpec() (*UserModelPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &UserModelPermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usermodelpermission.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(usermodelpermission.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(usermodelpermission.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usermodelpermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usermodelpermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.UserTable,
			Columns: []string{usermodelpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.RouteTable,
			Columns: []string{usermodelpermission.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RouteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserModelPermission.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserModelPermissionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserModelPermissionCreate) OnConflict(opts ...sql.ConflictOption) *UserModelPermissionUpsertOne {
	_c.conflict = opts
	return &UserModelPermissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserModelPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserModelPermissionCreate) OnConflictColumns(columns ...string) *UserModelPermissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserModelPermissionUpsertOne{
		create: _c,
	}
}

type (
	// UserModelPermissionUpsertOne is the builder for "upsert"-ing
	//  one UserModelPermission node.
	UserModelPermissionUpsertOne struct {
		create *UserModelPermissionCreate
	}

	// UserModelPermissionUpsert is the "OnConflict" setter.
	UserModelPermissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserModelPermissionUpsert) SetUserID(v int64) *UserModelPermissionUpsert {
	u.Set(usermodelpermission.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserModelPermissionUpsert) UpdateUserID() *UserModelPermissionUpsert {
	u.SetExcluded(usermodelpermission.FieldUserID)
	return u
}

// SetRouteID sets the "route_id" field.
func (u *UserModelPermissionUpsert) SetRouteID(v int64) *UserModelPermissionUpsert {
	u.Set(usermodelpermission.FieldRouteID, v)
	return u
}

// UpdateRouteID sets the "route_id" field to the value that was provided on create.
func (u *UserModelPermissionUpsert) UpdateRouteID() *UserModelPermissionUpsert {
	u.SetExcluded(usermodelpermission.FieldRouteID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UserModelPermissionUpsert) SetEnabled(v bool) *UserModelPermissionUpsert {
	u.Set(usermodelpermission.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UserModelPermissionUpsert) UpdateEnabled() *UserModelPermissionUpsert {
	u.SetExcluded(usermodelpermission.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserModelPermissionUpsert) SetUpdatedAt(v time.Time) *UserModelPermissionUpsert {
	u.Set(usermodelpermission.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserModelPermissionUpsert) UpdateUpdatedAt() *UserModelPermissionUpsert {
	u.SetExcluded(usermodelpermission.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserModelPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserModelPermissionUpsertOne) UpdateNewValues() *UserModelPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedBy(); exists {
			s.SetIgnore(usermodelpermission.FieldCreatedBy)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usermodelpermission.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserModelPermission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserModelPermissionUpsertOne) Ignore() *UserModelPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserModelPermissionUpsertOne) DoNothing() *UserModelPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserModelPermissionCreate.OnConflict
// documentation for more info.
func (u *UserModelPermissionUpsertOne) Update(set func(*UserModelPermissionUpsert)) *UserModelPermissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserModelPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserModelPermissionUpsertOne) SetUserID(v int64) *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserModelPermissionUpsertOne) UpdateUserID() *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetRouteID sets the "route_id" field.
func (u *UserModelPermissionUpsertOne) SetRouteID(v int64) *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetRouteID(v)
	})
}

// UpdateRouteID sets the "route_id" field to the value that was provided on create.
func (u *UserModelPermissionUpsertOne) UpdateRouteID() *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateRouteID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UserModelPermissionUpsertOne) SetEnabled(v bool) *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UserModelPermissionUpsertOne) UpdateEnabled() *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserModelPermissionUpsertOne) SetUpdatedAt(v time.Time) *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserModelPermissionUpsertOne) UpdateUpdatedAt() *UserModelPermissionUpsertOne {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserModelPermissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserModelPermissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserModelPermissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// UserModelPermissionCreateBulk is the builder for creating many UserModelPermission entities in bulk.
type UserModelPermissionCreateBulk struct {
	config
	err      error
	builders []*UserModelPermissionCreate
	conflict []sql.ConflictOption
}

// Save creates the UserModelPermission entities in the database.
func (_c *UserModelPermissionCreateBulk) Save(ctx context.Context) ([]*UserModelPermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserModelPermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserModelPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserModelPermissionCreateBulk) SaveX(ctx context.Context) []*UserModelPermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserModelPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserModelPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserModelPermission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserModelPermissionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserModelPermissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserModelPermissionUpsertBulk {
	_c.conflict = opts
	return &UserModelPermissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserModelPermission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserModelPermissionCreateBulk) OnConflictColumns(columns ...string) *UserModelPermissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserModelPermissionUpsertBulk{
		create: _c,
	}
}

// UserModelPermissionUpsertBulk is the builder for "upsert"-ing
// a bulk of UserModelPermission nodes.
type UserModelPermissionUpsertBulk struct {
	create *UserModelPermissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserModelPermission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserModelPermissionUpsertBulk) UpdateNewValues() *UserModelPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedBy(); exists {
				s.SetIgnore(usermodelpermission.FieldCreatedBy)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usermodelpermission.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserModelPermission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserModelPermissionUpsertBulk) Ignore() *UserModelPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserModelPermissionUpsertBulk) DoNothing() *UserModelPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserModelPermissionCreateBulk.OnConflict
// documentation for more info.
func (u *UserModelPermissionUpsertBulk) Update(set func(*UserModelPermissionUpsert)) *UserModelPermissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserModelPermissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserModelPermissionUpsertBulk) SetUserID(v int64) *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserModelPermissionUpsertBulk) UpdateUserID() *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateUserID()
	})
}

// SetRouteID sets the "route_id" field.
func (u *UserModelPermissionUpsertBulk) SetRouteID(v int64) *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetRouteID(v)
	})
}

// UpdateRouteID sets the "route_id" field to the value that was provided on create.
func (u *UserModelPermissionUpsertBulk) UpdateRouteID() *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateRouteID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UserModelPermissionUpsertBulk) SetEnabled(v bool) *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UserModelPermissionUpsertBulk) UpdateEnabled() *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserModelPermissionUpsertBulk) SetUpdatedAt(v time.Time) *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserModelPermissionUpsertBulk) UpdateUpdatedAt() *UserModelPermissionUpsertBulk {
	return u.Update(func(s *UserModelPermissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserModelPermissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserModelPermissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserModelPermissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserModelPermissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
