// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usermodelpermission"
)

// UserModelPermissionUpdate is the builder for updating UserModelPermission entities.
type UserModelPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *UserModelPermissionMutation
}

// Where appends a list predicates to the UserModelPermissionUpdate builder.
func (_u *UserModelPermissionUpdate) Where(ps ...predicate.UserModelPermission) *UserModelPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserModelPermissionUpdate) SetUserID(v int64) *UserModelPermissionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserModelPermissionUpdate) SetNillableUserID(v *int64) *UserModelPermissionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *UserModelPermissionUpdate) SetRouteID(v int64) *UserModelPermissionUpdate {
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *UserModelPermissionUpdate) SetNillableRouteID(v *int64) *UserModelPermissionUpdate {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserModelPermissionUpdate) SetEnabled(v bool) *UserModelPermissionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserModelPermissionUpdate) SetNillableEnabled(v *bool) *UserModelPermissionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserModelPermissionUpdate) SetUpdatedAt(v time.Time) *UserModelPermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserModelPermissionUpdate) SetUser(v *User) *UserModelPermissionUpdate {
	return _u.SetUserID(v.ID)
}

// SetRoute sets the "route" edge to the CompositeModelRoute entity.
func (_u *UserModelPermissionUpdate) SetRoute(v *CompositeModelRoute) *UserModelPermissionUpdate {
	return _u.SetRouteID(v.ID)
}

// Mutation returns the UserModelPermissionMutation object of the builder.
func (_u *UserModelPermissionUpdate) Mutation() *UserModelPermissionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserModelPermissionUpdate) ClearUser() *UserModelPermissionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRoute clears the "route" edge to the CompositeModelRoute entity.
func (_u *UserModelPermissionUpdate) ClearRoute() *UserModelPermissionUpdate {
	_u.mutation.ClearRoute()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserModelPermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserModelPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserModelPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserModelPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserModelPermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermodelpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserModelPermissionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserModelPermission.user"`)
	}
	if _u.mutation.RouteCleared() && len(_u.mutation.RouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserModelPermission.route"`)
	}
	return nil
}

func (_u *UserModelPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermodelpermission.Table, usermodelpermission.Columns, sqlgraph.NewFieldSpec(usermodelpermission.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(usermodelpermission.FieldRouteID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usermodelpermission.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermodelpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.UserTable,
			Columns: []string{usermodelpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.UserTable,
			Columns: []string{usermodelpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.RouteTable,
			Columns: []string{usermodelpermission.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.RouteTable,
			Columns: []string{usermodelpermission.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermodelpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserModelPermissionUpdateOne is the builder for updating a single UserModelPermission entity.
type UserModelPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserModelPermissionMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserModelPermissionUpdateOne) SetUserID(v int64) *UserModelPermissionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserModelPermissionUpdateOne) SetNillableUserID(v *int64) *UserModelPermissionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRouteID sets the "route_id" field.
func (_u *UserModelPermissionUpdateOne) SetRouteID(v int64) *UserModelPermissionUpdateOne {
	_u.mutation.SetRouteID(v)
	return _u
}

// SetNillableRouteID sets the "route_id" field if the given value is not nil.
func (_u *UserModelPermissionUpdateOne) SetNillableRouteID(v *int64) *UserModelPermissionUpdateOne {
	if v != nil {
		_u.SetRouteID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UserModelPermissionUpdateOne) SetEnabled(v bool) *UserModelPermissionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UserModelPermissionUpdateOne) SetNillableEnabled(v *bool) *UserModelPermissionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserModelPermissionUpdateOne) SetUpdatedAt(v time.Time) *UserModelPermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserModelPermissionUpdateOne) SetUser(v *User) *UserModelPermissionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRoute sets the "route" edge to the CompositeModelRoute entity.
func (_u *UserModelPermissionUpdateOne) SetRoute(v *CompositeModelRoute) *UserModelPermissionUpdateOne {
	return _u.SetRouteID(v.ID)
}

// Mutation returns the UserModelPermissionMutation object of the builder.
func (_u *UserModelPermissionUpdateOne) Mutation() *UserModelPermissionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserModelPermissionUpdateOne) ClearUser() *UserModelPermissionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRoute clears the "route" edge to the CompositeModelRoute entity.
func (_u *UserModelPermissionUpdateOne) ClearRoute() *UserModelPermissionUpdateOne {
	_u.mutation.ClearRoute()
	return _u
}

// Where appends a list predicates to the UserModelPermissionUpdate builder.
func (_u *UserModelPermissionUpdateOne) Where(ps ...predicate.UserModelPermission) *UserModelPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserModelPermissionUpdateOne) Select(field string, fields ...string) *UserModelPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserModelPermission entity.
func (_u *UserModelPermissionUpdateOne) Save(ctx context.Context) (*UserModelPermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserModelPermissionUpdateOne) SaveX(ctx context.Context) *UserModelPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserModelPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserModelPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserModelPermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usermodelpermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserModelPermissionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserModelPermission.user"`)
	}
	if _u.mutation.RouteCleared() && len(_u.mutation.RouteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserModelPermission.route"`)
	}
	return nil
}

func (_u *UserModelPermissionUpdateOne) sqlSave(ctx context.Context) (_node *UserModelPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usermodelpermission.Table, usermodelpermission.Columns, sqlgraph.NewFieldSpec(usermodelpermission.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(usermodelpermission.FieldRouteID, field.TypeInt64))
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "UserModelPermission.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.RouteID(); !ok {
		return nil, &ValidationError{Name: "route_id", err: errors.New(`ent: missing "UserModelPermission.route_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !usermodelpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usermodelpermission.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usermodelpermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.UserTable,
			Columns: []string{usermodelpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.UserTable,
			Columns: []string{usermodelpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RouteCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.RouteTable,
			Columns: []string{usermodelpermission.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RouteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usermodelpermission.RouteTable,
			Columns: []string{usermodelpermission.RouteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserModelPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usermodelpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
