// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/wallettransaction"
	"github.com/shopspring/decimal"
)

// WalletTransaction is the model entity for the WalletTransaction schema.
type WalletTransaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Type holds the value of the "type" field.
	Type wallettransaction.Type `json:"type,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BalanceBefore holds the value of the "balance_before" field.
	BalanceBefore decimal.Decimal `json:"balance_before,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter decimal.Decimal `json:"balance_after,omitempty"`
	// ReferenceType holds the value of the "reference_type" field.
	ReferenceType string `json:"reference_type,omitempty"`
	// ReferenceID holds the value of the "reference_id" field.
	ReferenceID string `json:"reference_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint string `json:"request_fingerprint,omitempty"`
	// OperatorID holds the value of the "operator_id" field.
	OperatorID *int64 `json:"operator_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WalletTransactionQuery when eager-loading is set.
	Edges        WalletTransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WalletTransactionEdges holds the relations/edges for other nodes in the graph.
type WalletTransactionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Operator holds the value of the operator edge.
	Operator *User `json:"operator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WalletTransactionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OperatorOrErr returns the Operator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WalletTransactionEdges) OperatorOrErr() (*User, error) {
	if e.Operator != nil {
		return e.Operator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "operator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WalletTransaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wallettransaction.FieldMetadata:
			values[i] = new([]byte)
		case wallettransaction.FieldAmount, wallettransaction.FieldBalanceBefore, wallettransaction.FieldBalanceAfter:
			values[i] = new(decimal.Decimal)
		case wallettransaction.FieldID, wallettransaction.FieldUserID, wallettransaction.FieldOperatorID:
			values[i] = new(sql.NullInt64)
		case wallettransaction.FieldType, wallettransaction.FieldCurrency, wallettransaction.FieldReferenceType, wallettransaction.FieldReferenceID, wallettransaction.FieldIdempotencyKey, wallettransaction.FieldRequestFingerprint, wallettransaction.FieldSource, wallettransaction.FieldNote:
			values[i] = new(sql.NullString)
		case wallettransaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WalletTransaction fields.
func (_m *WalletTransaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wallettransaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case wallettransaction.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case wallettransaction.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = wallettransaction.Type(value.String)
			}
		case wallettransaction.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				_m.Amount = *value
			}
		case wallettransaction.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case wallettransaction.FieldBalanceBefore:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value != nil {
				_m.BalanceBefore = *value
			}
		case wallettransaction.FieldBalanceAfter:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value != nil {
				_m.BalanceAfter = *value
			}
		case wallettransaction.FieldReferenceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_type", values[i])
			} else if value.Valid {
				_m.ReferenceType = value.String
			}
		case wallettransaction.FieldReferenceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference_id", values[i])
			} else if value.Valid {
				_m.ReferenceID = value.String
			}
		case wallettransaction.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case wallettransaction.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = value.String
			}
		case wallettransaction.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = new(int64)
				*_m.OperatorID = value.Int64
			}
		case wallettransaction.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case wallettransaction.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case wallettransaction.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case wallettransaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WalletTransaction.
// This includes values selected through modifiers, order, etc.
func (_m *WalletTransaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the WalletTransaction entity.
func (_m *WalletTransaction) QueryUser() *UserQuery {
	return NewWalletTransactionClient(_m.config).QueryUser(_m)
}

// QueryOperator queries the "operator" edge of the WalletTransaction entity.
func (_m *WalletTransaction) QueryOperator() *UserQuery {
	return NewWalletTransactionClient(_m.config).QueryOperator(_m)
}

// Update returns a builder for updating this WalletTransaction.
// Note that you need to call WalletTransaction.Unwrap() before calling this method if this WalletTransaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WalletTransaction) Update() *WalletTransactionUpdateOne {
	return NewWalletTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WalletTransaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WalletTransaction) Unwrap() *WalletTransaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WalletTransaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WalletTransaction) String() string {
	var builder strings.Builder
	builder.WriteString("WalletTransaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	builder.WriteString("reference_type=")
	builder.WriteString(_m.ReferenceType)
	builder.WriteString(", ")
	builder.WriteString("reference_id=")
	builder.WriteString(_m.ReferenceID)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=")
	builder.WriteString(_m.RequestFingerprint)
	builder.WriteString(", ")
	if v := _m.OperatorID; v != nil {
		builder.WriteString("operator_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WalletTransactions is a parsable slice of WalletTransaction.
type WalletTransactions []*WalletTransaction
