// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/wallettransaction"
	"github.com/shopspring/decimal"
)

// WalletTransactionCreate is the builder for creating a WalletTransaction entity.
type WalletTransactionCreate struct {
	config
	mutation *WalletTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *WalletTransactionCreate) SetUserID(v int64) *WalletTransactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *WalletTransactionCreate) SetType(v wallettransaction.Type) *WalletTransactionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *WalletTransactionCreate) SetAmount(v decimal.Decimal) *WalletTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *WalletTransactionCreate) SetCurrency(v string) *WalletTransactionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableCurrency(v *string) *WalletTransactionCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *WalletTransactionCreate) SetBalanceBefore(v decimal.Decimal) *WalletTransactionCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *WalletTransactionCreate) SetBalanceAfter(v decimal.Decimal) *WalletTransactionCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetReferenceType sets the "reference_type" field.
func (_c *WalletTransactionCreate) SetReferenceType(v string) *WalletTransactionCreate {
	_c.mutation.SetReferenceType(v)
	return _c
}

// SetReferenceID sets the "reference_id" field.
func (_c *WalletTransactionCreate) SetReferenceID(v string) *WalletTransactionCreate {
	_c.mutation.SetReferenceID(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *WalletTransactionCreate) SetIdempotencyKey(v string) *WalletTransactionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *WalletTransactionCreate) SetRequestFingerprint(v string) *WalletTransactionCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetOperatorID sets the "operator_id" field.
func (_c *WalletTransactionCreate) SetOperatorID(v int64) *WalletTransactionCreate {
	_c.mutation.SetOperatorID(v)
	return _c
}

// SetNillableOperatorID sets the "operator_id" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableOperatorID(v *int64) *WalletTransactionCreate {
	if v != nil {
		_c.SetOperatorID(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *WalletTransactionCreate) SetSource(v string) *WalletTransactionCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *WalletTransactionCreate) SetNote(v string) *WalletTransactionCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableNote(v *string) *WalletTransactionCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *WalletTransactionCreate) SetMetadata(v map[string]interface{}) *WalletTransactionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WalletTransactionCreate) SetCreatedAt(v time.Time) *WalletTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WalletTransactionCreate) SetNillableCreatedAt(v *time.Time) *WalletTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *WalletTransactionCreate) SetUser(v *User) *WalletTransactionCreate {
	return _c.SetUserID(v.ID)
}

// SetOperator sets the "operator" edge to the User entity.
func (_c *WalletTransactionCreate) SetOperator(v *User) *WalletTransactionCreate {
	return _c.SetOperatorID(v.ID)
}

// Mutation returns the WalletTransactionMutation object of the builder.
func (_c *WalletTransactionCreate) Mutation() *WalletTransactionMutation {
	return _c.mutation
}

// Save creates the WalletTransaction in the database.
func (_c *WalletTransactionCreate) Save(ctx context.Context) (*WalletTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WalletTransactionCreate) SaveX(ctx context.Context) *WalletTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WalletTransactionCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := wallettransaction.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Note(); !ok {
		v := wallettransaction.DefaultNote
		_c.mutation.SetNote(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := wallettransaction.DefaultMetadata()
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wallettransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WalletTransactionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WalletTransaction.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "WalletTransaction.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := wallettransaction.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "WalletTransaction.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "WalletTransaction.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := wallettransaction.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		return &ValidationError{Name: "balance_before", err: errors.New(`ent: missing required field "WalletTransaction.balance_before"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "WalletTransaction.balance_after"`)}
	}
	if _, ok := _c.mutation.ReferenceType(); !ok {
		return &ValidationError{Name: "reference_type", err: errors.New(`ent: missing required field "WalletTransaction.reference_type"`)}
	}
	if v, ok := _c.mutation.ReferenceType(); ok {
		if err := wallettransaction.ReferenceTypeValidator(v); err != nil {
			return &ValidationError{Name: "reference_type", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.reference_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReferenceID(); !ok {
		return &ValidationError{Name: "reference_id", err: errors.New(`ent: missing required field "WalletTransaction.reference_id"`)}
	}
	if v, ok := _c.mutation.ReferenceID(); ok {
		if err := wallettransaction.ReferenceIDValidator(v); err != nil {
			return &ValidationError{Name: "reference_id", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.reference_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "WalletTransaction.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := wallettransaction.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		return &ValidationError{Name: "request_fingerprint", err: errors.New(`ent: missing required field "WalletTransaction.request_fingerprint"`)}
	}
	if v, ok := _c.mutation.RequestFingerprint(); ok {
		if err := wallettransaction.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.request_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "WalletTransaction.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := wallettransaction.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "WalletTransaction.note"`)}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := wallettransaction.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "WalletTransaction.note": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "WalletTransaction.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WalletTransaction.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "WalletTransaction.user"`)}
	}
	return nil
}

func (_c *WalletTransactionCreate) sqlSave(ctx context.Context) (*WalletTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WalletTransactionCreate) createSpec() (*WalletTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &WalletTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wallettransaction.Table, sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(wallettransaction.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(wallettransaction.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(wallettransaction.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(wallettransaction.FieldBalanceBefore, field.TypeFloat64, value)
		_node.BalanceBefore = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(wallettransaction.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.ReferenceType(); ok {
		_spec.SetField(wallettransaction.FieldReferenceType, field.TypeString, value)
		_node.ReferenceType = value
	}
	if value, ok := _c.mutation.ReferenceID(); ok {
		_spec.SetField(wallettransaction.FieldReferenceID, field.TypeString, value)
		_node.ReferenceID = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(wallettransaction.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(wallettransaction.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(wallettransaction.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(wallettransaction.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(wallettransaction.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wallettransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallettransaction.UserTable,
			Columns: []string{wallettransaction.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OperatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wallettransaction.OperatorTable,
			Columns: []string{wallettransaction.OperatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OperatorID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletTransaction.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletTransactionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletTransactionCreate) OnConflict(opts ...sql.ConflictOption) *WalletTransactionUpsertOne {
	_c.conflict = opts
	return &WalletTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletTransactionCreate) OnConflictColumns(columns ...string) *WalletTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletTransactionUpsertOne{
		create: _c,
	}
}

type (
	// WalletTransactionUpsertOne is the builder for "upsert"-ing
	//  one WalletTransaction node.
	WalletTransactionUpsertOne struct {
		create *WalletTransactionCreate
	}

	// WalletTransactionUpsert is the "OnConflict" setter.
	WalletTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletTransactionUpsertOne) UpdateNewValues() *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(wallettransaction.FieldUserID)
		}
		if _, exists := u.create.mutation.GetType(); exists {
			s.SetIgnore(wallettransaction.FieldType)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(wallettransaction.FieldAmount)
		}
		if _, exists := u.create.mutation.Currency(); exists {
			s.SetIgnore(wallettransaction.FieldCurrency)
		}
		if _, exists := u.create.mutation.BalanceBefore(); exists {
			s.SetIgnore(wallettransaction.FieldBalanceBefore)
		}
		if _, exists := u.create.mutation.BalanceAfter(); exists {
			s.SetIgnore(wallettransaction.FieldBalanceAfter)
		}
		if _, exists := u.create.mutation.ReferenceType(); exists {
			s.SetIgnore(wallettransaction.FieldReferenceType)
		}
		if _, exists := u.create.mutation.ReferenceID(); exists {
			s.SetIgnore(wallettransaction.FieldReferenceID)
		}
		if _, exists := u.create.mutation.IdempotencyKey(); exists {
			s.SetIgnore(wallettransaction.FieldIdempotencyKey)
		}
		if _, exists := u.create.mutation.RequestFingerprint(); exists {
			s.SetIgnore(wallettransaction.FieldRequestFingerprint)
		}
		if _, exists := u.create.mutation.OperatorID(); exists {
			s.SetIgnore(wallettransaction.FieldOperatorID)
		}
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(wallettransaction.FieldSource)
		}
		if _, exists := u.create.mutation.Note(); exists {
			s.SetIgnore(wallettransaction.FieldNote)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(wallettransaction.FieldMetadata)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(wallettransaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WalletTransactionUpsertOne) Ignore() *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletTransactionUpsertOne) DoNothing() *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletTransactionCreate.OnConflict
// documentation for more info.
func (u *WalletTransactionUpsertOne) Update(set func(*WalletTransactionUpsert)) *WalletTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *WalletTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WalletTransactionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WalletTransactionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WalletTransactionCreateBulk is the builder for creating many WalletTransaction entities in bulk.
type WalletTransactionCreateBulk struct {
	config
	err      error
	builders []*WalletTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the WalletTransaction entities in the database.
func (_c *WalletTransactionCreateBulk) Save(ctx context.Context) ([]*WalletTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WalletTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WalletTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WalletTransactionCreateBulk) SaveX(ctx context.Context) []*WalletTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WalletTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WalletTransactionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *WalletTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *WalletTransactionUpsertBulk {
	_c.conflict = opts
	return &WalletTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *WalletTransactionCreateBulk) OnConflictColumns(columns ...string) *WalletTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &WalletTransactionUpsertBulk{
		create: _c,
	}
}

// WalletTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of WalletTransaction nodes.
type WalletTransactionUpsertBulk struct {
	create *WalletTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *WalletTransactionUpsertBulk) UpdateNewValues() *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(wallettransaction.FieldUserID)
			}
			if _, exists := b.mutation.GetType(); exists {
				s.SetIgnore(wallettransaction.FieldType)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(wallettransaction.FieldAmount)
			}
			if _, exists := b.mutation.Currency(); exists {
				s.SetIgnore(wallettransaction.FieldCurrency)
			}
			if _, exists := b.mutation.BalanceBefore(); exists {
				s.SetIgnore(wallettransaction.FieldBalanceBefore)
			}
			if _, exists := b.mutation.BalanceAfter(); exists {
				s.SetIgnore(wallettransaction.FieldBalanceAfter)
			}
			if _, exists := b.mutation.ReferenceType(); exists {
				s.SetIgnore(wallettransaction.FieldReferenceType)
			}
			if _, exists := b.mutation.ReferenceID(); exists {
				s.SetIgnore(wallettransaction.FieldReferenceID)
			}
			if _, exists := b.mutation.IdempotencyKey(); exists {
				s.SetIgnore(wallettransaction.FieldIdempotencyKey)
			}
			if _, exists := b.mutation.RequestFingerprint(); exists {
				s.SetIgnore(wallettransaction.FieldRequestFingerprint)
			}
			if _, exists := b.mutation.OperatorID(); exists {
				s.SetIgnore(wallettransaction.FieldOperatorID)
			}
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(wallettransaction.FieldSource)
			}
			if _, exists := b.mutation.Note(); exists {
				s.SetIgnore(wallettransaction.FieldNote)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(wallettransaction.FieldMetadata)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(wallettransaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WalletTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WalletTransactionUpsertBulk) Ignore() *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WalletTransactionUpsertBulk) DoNothing() *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WalletTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *WalletTransactionUpsertBulk) Update(set func(*WalletTransactionUpsert)) *WalletTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WalletTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *WalletTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the WalletTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for WalletTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WalletTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
