// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/wallettransaction"
)

// WalletTransactionUpdate is the builder for updating WalletTransaction entities.
type WalletTransactionUpdate struct {
	config
	hooks    []Hook
	mutation *WalletTransactionMutation
}

// Where appends a list predicates to the WalletTransactionUpdate builder.
func (_u *WalletTransactionUpdate) Where(ps ...predicate.WalletTransaction) *WalletTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRefundID sets the "refund" edge to the WalletTransaction entity by ID.
func (_u *WalletTransactionUpdate) SetRefundID(id int64) *WalletTransactionUpdate {
	_u.mutation.SetRefundID(id)
	return _u
}

// SetNillableRefundID sets the "refund" edge to the WalletTransaction entity by ID if the given value is not nil.
func (_u *WalletTransactionUpdate) SetNillableRefundID(id *int64) *WalletTransactionUpdate {
	if id != nil {
		_u = _u.SetRefundID(*id)
	}
	return _u
}

// SetRefund sets the "refund" edge to the WalletTransaction entity.
func (_u *WalletTransactionUpdate) SetRefund(v *WalletTransaction) *WalletTransactionUpdate {
	return _u.SetRefundID(v.ID)
}

// Mutation returns the WalletTransactionMutation object of the builder.
func (_u *WalletTransactionUpdate) Mutation() *WalletTransactionMutation {
	return _u.mutation
}

// ClearRefund clears the "refund" edge to the WalletTransaction entity.
func (_u *WalletTransactionUpdate) ClearRefund() *WalletTransactionUpdate {
	_u.mutation.ClearRefund()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WalletTransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WalletTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletTransactionUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WalletTransaction.user"`)
	}
	return nil
}

func (_u *WalletTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallettransaction.Table, wallettransaction.Columns, sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RefundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   wallettransaction.RefundTable,
			Columns: []string{wallettransaction.RefundColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   wallettransaction.RefundTable,
			Columns: []string{wallettransaction.RefundColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallettransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WalletTransactionUpdateOne is the builder for updating a single WalletTransaction entity.
type WalletTransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletTransactionMutation
}

// SetRefundID sets the "refund" edge to the WalletTransaction entity by ID.
func (_u *WalletTransactionUpdateOne) SetRefundID(id int64) *WalletTransactionUpdateOne {
	_u.mutation.SetRefundID(id)
	return _u
}

// SetNillableRefundID sets the "refund" edge to the WalletTransaction entity by ID if the given value is not nil.
func (_u *WalletTransactionUpdateOne) SetNillableRefundID(id *int64) *WalletTransactionUpdateOne {
	if id != nil {
		_u = _u.SetRefundID(*id)
	}
	return _u
}

// SetRefund sets the "refund" edge to the WalletTransaction entity.
func (_u *WalletTransactionUpdateOne) SetRefund(v *WalletTransaction) *WalletTransactionUpdateOne {
	return _u.SetRefundID(v.ID)
}

// Mutation returns the WalletTransactionMutation object of the builder.
func (_u *WalletTransactionUpdateOne) Mutation() *WalletTransactionMutation {
	return _u.mutation
}

// ClearRefund clears the "refund" edge to the WalletTransaction entity.
func (_u *WalletTransactionUpdateOne) ClearRefund() *WalletTransactionUpdateOne {
	_u.mutation.ClearRefund()
	return _u
}

// Where appends a list predicates to the WalletTransactionUpdate builder.
func (_u *WalletTransactionUpdateOne) Where(ps ...predicate.WalletTransaction) *WalletTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WalletTransactionUpdateOne) Select(field string, fields ...string) *WalletTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WalletTransaction entity.
func (_u *WalletTransactionUpdateOne) Save(ctx context.Context) (*WalletTransaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletTransactionUpdateOne) SaveX(ctx context.Context) *WalletTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WalletTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletTransactionUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WalletTransaction.user"`)
	}
	return nil
}

func (_u *WalletTransactionUpdateOne) sqlSave(ctx context.Context) (_node *WalletTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallettransaction.Table, wallettransaction.Columns, sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WalletTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallettransaction.FieldID)
		for _, f := range fields {
			if !wallettransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wallettransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.RefundCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   wallettransaction.RefundTable,
			Columns: []string{wallettransaction.RefundColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefundIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   wallettransaction.RefundTable,
			Columns: []string{wallettransaction.RefundColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallettransaction.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WalletTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallettransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
